server:
  port: 9000

spring:
  datasource:
    #Dev
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

    #AWS
    #url: jdbc:postgresql://postgres.cfjjta8rfcxg.us-east-1.rds.amazonaws.com:5432/postgres
    #username: postgres
    #password: password
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR